### ISSUE TITLE
maven 在初始化数据库的时候报错

### ISSUE THREAD

**Issue by dreamkidd** [thinkgem/jeesite#172]
# maven在初始化数据库的时候报错
在命令行下运行 `mvn -X antrun:run -Pinit-db`出现错误
错误信息如下
``` err
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (default-cli) on project wandamanage: An Ant BuildException has occured: org.dbunit.database.AmbiguousTableNameException: ACT_GE_BYTEARRAY
[ERROR] around Ant part ...<dbunit password="${jdbc.password}" driver="${jdbc.driver}" userid="${jdbc.username}" url="${jdbc.url}">... @ 22:107 in /Users/Dream_Kidd/github/jeesite/target/antrun/build-main.xml
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (default-cli) on project wandamanage: An Ant BuildException has occured: org.dbunit.database.AmbiguousTableNameException: ACT_GE_BYTEARRAY
around Ant part ...<dbunit password="${jdbc.password}" driver="${jdbc.driver}" userid="${jdbc.username}" url="${jdbc.url}">... @ 22:107 in /Users/Dream_Kidd/github/jeesite/target/antrun/build-main.xml
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: An Ant BuildException has occured: org.dbunit.database.AmbiguousTableNameException: ACT_GE_BYTEARRAY
around Ant part ...<dbunit password="${jdbc.password}" driver="${jdbc.driver}" userid="${jdbc.username}" url="${jdbc.url}">... @ 22:107 in /Users/Dream_Kidd/github/jeesite/target/antrun/build-main.xml
	at org.apache.maven.plugin.antrun.AntRunMojo.execute(AntRunMojo.java:355)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: /Users/Dream_Kidd/github/jeesite/target/antrun/build-main.xml:22: org.dbunit.database.AmbiguousTableNameException: ACT_GE_BYTEARRAY
	at org.dbunit.ant.DbUnitTask.execute(DbUnitTask.java:385)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:390)
	at org.apache.tools.ant.Target.performTasks(Target.java:411)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
	at org.apache.maven.plugin.antrun.AntRunMojo.execute(AntRunMojo.java:327)
	... 22 more
Caused by: org.dbunit.database.AmbiguousTableNameException: ACT_GE_BYTEARRAY
	at org.dbunit.dataset.OrderedTableNameMap.add(OrderedTableNameMap.java:198)
	at org.dbunit.database.DatabaseDataSet.initialize(DatabaseDataSet.java:231)
	at org.dbunit.database.DatabaseDataSet.getTableMetaData(DatabaseDataSet.java:281)
	at org.dbunit.operation.AbstractOperation.getOperationMetaData(AbstractOperation.java:80)
	at org.dbunit.operation.AbstractBatchOperation.execute(AbstractBatchOperation.java:140)
	at org.dbunit.operation.TransactionOperation.execute(TransactionOperation.java:78)
	at org.dbunit.ant.Operation.execute(Operation.java:192)
	at org.dbunit.ant.DbUnitTask.execute(DbUnitTask.java:380)
	... 34 more
[ERROR]
```

**Comment by csfrez** [comment]
请问错误解决了嘛？我现在也遇到了同样的问题。

**Comment by syncxplus** [comment]
使用oracle遇到同样的问题，请问是怎么解决的

**Comment by will2012** [comment]
如何解决的？
