### ISSUE TITLE
大写的表名报错，在mysql条件下

### ISSUE THREAD

**Issue by gsgsdtc** [thinkgem/jeesite#208]
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'jeesite.OA_NOTIFY' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'jeesite.SYS_USER' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

这个能不能改一下，有三个xml文件
不知道是不是我的环境问题，但至少会错，改一下

**Comment by gsgsdtc** [comment]
OA_TEST_AUDIT 这张表用大写的，但xml的sql你用小写的，也报错了，希望能进行更改

**Comment by gsgsdtc** [comment]
还有生成的数据也是区分大小写的

**Comment by dreamkidd** [comment]
设置数据库忽略大小写即可

**Comment by jpr1990** [comment]
我也遇到这个问题，已经本地修改了，不太会使用github，否则就拉个分支提交代码了

**Comment by ghaseminya** [comment]
Hi @jpr1990 
Did this problem solve?
I run db initialization on linux but my problem is db insertion.

**Comment by d87335903** [comment]
@ghaseminya 
what's your problem ?  you can paste your exception stack here .
