### ISSUE TITLE
jeesite怎么在main方法中调用service注解的类

### ISSUE THREAD

**Issue by Miraclelucy** [thinkgem/jeesite#471]
`public static void main (String[] args ){
        ApplicationContext ctx = new ClassPathXmlApplicationContext("spring-context.xml");
        ImportGamexxjh5 importGamexxjh5=ctx.getBean("importGamexxjh5", ImportGamexxjh5.class);
        String tablename="order_180528";
        importGamexxjh5.run(tablename);
    }`
报错了：
`Exception in thread "main" org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [com.thinkgem.jeesite.modules.sys.security.FormAuthenticationFilter]; nested exception is org.springframework.core.NestedIOException: Failed to load class [javax.servlet.Filter]; nested exception is java.lang.ClassNotFoundException: javax.servlet.Filter
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:187)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:321)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:243)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:273)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:98)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:681)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:523)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at com.thinkgem.jeesite.modules.gamexxjh5.task.ImportGamexxjh5.main(ImportGamexxjh5.java:80)`

**Comment by txjchu** [comment]
我是在main方法中这样用
```
		String[] locations = {"xxx\spring-context.xml", "xxx\spring-context-activiti.xml", "xxx\spring-context-shiro.xml", "xxx\spring-mvc.xml"};
		ApplicationContext applicationContext = new FileSystemXmlApplicationContext(locations);
		SpringContextHolder springContextHolder = new SpringContextHolder();
		springContextHolder.setApplicationContext(applicationContext);
		AreaService areaService = springContextHolder.getBean( AreaService.class);
```
但是现在报了几个异常：
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shiroFilter' ...
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'securityManager' defined in file...
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'systemAuthorizingRealm': Unsatisfied dependency expressed through field 'request'; nested exception is ...
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'javax.servlet.http.HttpServletRequest' available: expected at least 1 bean which qualifies as autowire candidate.......

所以，还没找到解决办法
